POST http://localhost:3001/api/blogs
content-type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImdyYXBoaWNuYXBraW4yIiwiaWQiOiI1ZmEzMjQwYzgwMTQxYTc5ZThjM2Y1MDEiLCJpYXQiOjE2MDQ3MTI1NDF9.X-2QX9ILn1jcBzu5cboBv-Q7H3KAe7umbK5aSJFAyQQ

{
  "title": "test 122",
  "author": "jc",
  "url": "graphicnapkin.com",
  "userId": "5f9a1d242d192ce65c092f70"

}